### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iban79** [Jytesh/hcaptcha-solver#2]
Microsoft Windows [Versión 10.0.19042.572]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.

D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master>node t.js
Wrong Response. Retrying.
Wrong Challenge Type. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
Wrong Response. Retrying.
HTTPError: Response code 429 (Too Many Requests)
    at Request.<anonymous> (D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1619990648819,
    socket: 1619990648820,
    lookup: 1619990648822,
    connect: 1619990648842,
    secureConnect: 1619990648946,
    upload: 1619990648946,
    response: 1619990649174,
    end: 1619990649174,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 20,
      tls: 104,
      request: 0,
      firstByte: 228,
      download: 0,
      total: 355
    }
  }
}
(node:13868) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'generated_pass_UUID' of undefined
    at tryToSolve (D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master\node_modules\hcaptcha-solver\hcaptcha.js:95:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async solveCaptcha (D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master\node_modules\hcaptcha-solver\hcaptcha.js:183:22)
    at async hcaptchaToken (D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master\node_modules\hcaptcha-solver\hcaptcha.js:207:10)
    at async D:\Descargas\hcaptcha-solver-Ultimo\hcaptcha-solver-master\t.js:8:17
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by iban79** [comment]
Any idea why I get this error?
Thanks.

**Comment by Jytesh** [comment]
Solver fails to solve it before hitting rate limit, working to make it fail silently and wait out ratelimit

**Comment by iban79** [comment]
Thanks for answering.
